### PR TITLE
just return h3 results, not subsites

### PR DESCRIPTION
**Pull request by m3nu**
Some sites display additional results from the same page. Your script returns them all. I would find it more intuitive, if only the 10 main results are returned.

### CODE REVIEW

**Comment by pawelad** [comment]
A actually think that you fixed the issue above with `only_standard` parameter, so I just wanted to mention that here in case anyone else finds this thread.

**Comment by Mitchelle123** [comment]
I think for the majority of users, these extra results are more confusing than useful. It took me some time to figure, where the extra URLs come from. But it can be an option of course.

**Comment by pawelad** [comment]
@Mitchelle123 I agree, but I just wanted to let anybody that stumbles onto here that this feature is indeed implemented.

**Comment by m3nu** [comment]
OK. So this can be closed now.

**Pull request closed without merging**
