### PR TITLE
Add parameter to allow inclusion of Google domain links in results

### PR DESCRIPTION
**Pull request by HemanthMTH**

### CODE REVIEW

**Comment by goodmainelder** [comment]
Is this why I can't get results for `site:play.google.com/store/apps`?

**Comment by HemanthMTH** [comment]
> Is this why I can't get results for `site:play.google.com/store/apps`?

**Comment by HemanthMTH** [comment]
> Is this why I can't get results for `site:play.google.com/store/apps`?

Yes.

**Comment by HemanthMTH** [comment]
reopen.

**Comment by MarioVilas** [comment]
Thank you very much!

**Pull request merged**
