### PR TITLE
Rearranged package structure to more standard form

### PR DESCRIPTION
**Pull request by valhallasw**
Changes:
 - script is no longer part of the library, but in the seperate scripts
   directory
 - library is now packaged as google/__init__.py. The old packaging
   layout sometimes caused issues with setuptools, resulting in
       "TypeError: ('Not a package:', 'google')
   when trying to import any package

### CODE REVIEW

**Comment by MarioVilas** [comment]
Thanks! I had never tried using is as a dependency with setuptools so I never noticed the problem. (In fact when I used it myself I never installed it as a package at all, just dumped the .py somewhere and ran it from command line).

**Comment by jayvdb** [comment]
Could you do a pypi release, as this isnt actually fixed until setuptools can download and install the 'google' dependency that doesnt have this bug.

**Comment by MarioVilas** [comment]
I think I'll have to work a bit more on it, I just tried the following and this happened:

```
Mario@Mario-PC ~/google
$ python setup.py --help
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-0.9.6.tar.gz
Extracting in /tmp/tmp5lWRMe
Now working in /tmp/tmp5lWRMe/setuptools-0.9.6
Building a Setuptools egg in /home/Mario/google
/home/Mario/google/setuptools-0.9.6-py2.7.egg
Common commands: (see '--help-commands' for more)

  setup.py build      will build the package underneath 'build/'
  setup.py install    will install the package

Global options:
  --verbose (-v)      run verbosely (default)
  --quiet (-q)        run quietly (turns verbosity off)
  --dry-run (-n)      don't actually do anything
  --help (-h)         show detailed help message
  --no-user-cfg       ignore pydistutils.cfg in your home directory
  --command-packages  list of packages that provide distutils commands

Information display options (just display information, ignore any commands)
  --help-commands     list all available commands
  --name              print package name
  --version (-V)      print package version
  --fullname          print <package name>-<version>
  --author            print the author's name
  --author-email      print the author's email address
  --maintainer        print the maintainer's name
  --maintainer-email  print the maintainer's email address
  --contact           print the maintainer's name if known, else the author's
  --contact-email     print the maintainer's email address if known, else the
                      author's
  --url               print the URL for this package
  --license           print the license of the package
  --licence           alias for --license
  --description       print the package description
  --long-description  print the long package description
  --platforms         print the list of platforms
  --classifiers       print the list of classifiers
  --keywords          print the list of keywords
  --provides          print the list of packages/modules provided
  --requires          print the list of packages/modules required
  --obsoletes         print the list of packages/modules made obsolete

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
```

It shouldn't be trying to download setuptools before getting a help message...

**Comment by valhallasw** [comment]
I think that's just the

```
from ez_setup import use_setuptools
use_setuptools()
```

running -- it should still happen after reverting my change.

**Comment by MarioVilas** [comment]
Indeed, it happened after I reverted the changes. Seems like I tried to make it compatible with setuptools before and then completely forgot about it. I'll remove that and bring back your changes, then test it to make sure I didn't break anything.

**Comment by MarioVilas** [comment]
Ok, it seems to be working normally now. Can you try out if the dependency is resolved correctly?

**Comment by valhallasw** [comment]
install_requires requires setuptools (distutils doesn't support it). I think you can probably safely just use

```
from setuptools import setup
```

as most people would have setuptools installed. That's how the Python Packaging Authority suggests it, at least: https://github.com/pypa/sampleproject/blob/master/setup.py

**Comment by MarioVilas** [comment]
Good idea. I'll leave it in a try/except in case setuptools isn't installed for some reason, can't hurt.

**Pull request merged**
